name: Research_Project
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.1
  - debugpy=1.6.7
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - -r requirements.txt